##===- lib/Transforms/FDOInliner/Makefile ------------------*- Makefile -*-===##
#
#                     The LLVM Compiler Infrastructure
#
#  Paul Berube, June 13, 2011
##===----------------------------------------------------------------------===##

LEVEL = ../../..
LIBRARYNAME = LLVMfdo
BUILD_ARCHIVE=1

include $(LEVEL)/Makefile.common

